---
- hosts: 172.31.87.93
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
      name: apache2
      state: present

  - name: copy file to ansible node
    copy: 
       src: staticfile.txt
       dest: /home/ubuntu/mystaticfile.txt
    notify : restart webserver

  - name: copy index.j2 file into ansible node
    template: 
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restart webserver


    handlers: 
    - name: restart webserver
      service: 
         name: apache2
         state: restarted
