---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install wevserver on ubuntu ansible nodes
    apt: 
      name: apache2
      state: present
    when : ansible_os_family == "Debian"
  - name: i want to start start webeserver on ubuntu nodes
    service :
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
  - name: i want to install webserver on redhat ansible nodes
    yum: 
       name: httpd
       state: present
    when : ansible_os_family == "RedHat"
  - name : i want to start webserver on redhat ansible nodes
    service : 
       name : httpd
       state : started
    when : ansible_os_family == "RedHat"
    